services:
  - type: web
    name: mern-shop
    runtime: node
    plan: free
    rootDir: beeskilled-assignments/week-4
    buildCommand: npm install && npm install --prefix frontend && npm run build --prefix frontend
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
      - key: JWT_SECRET
        sync: false
      - key: MONGO_URI
        sync: false
      - key: PAGINATION_MAX_LIMIT
        value: 12
    healthCheckPath: /
